from typing import Any

import numpy

def dbfs(value: float) -> float: ...
def rms(samples: list[float]) -> float: ...
def peak(samples: list[float]) -> float: ...
def windowed_rms(samples: list[float], window: int) -> list[float]: ...
def windowed_peak(samples: list[float], window: int) -> list[float]: ...
def autoscale_symmetric(min_y: float, max_y: float) -> tuple[float, float]: ...
def bucket_min_max_i32(samples: list[int], buckets: int) -> list[tuple[float, float, bool]]: ...
def bucket_min_max_i32_np(
    samples: numpy.ndarray[Any, numpy.dtype[numpy.int32]],
    start: int,
    end: int,
    buckets: int,
) -> list[tuple[float, float, bool]]: ...
